In [4]:
import torch
import numpy as np
from torch import nn

print("### Task 1.1: Tạo Tensor ###\n")

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand}\n")

print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

### Task 1.1: Tạo Tensor ###

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.9106, 0.5921],
        [0.8709, 0.4779]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


In [5]:
print("\n### Task 1.2: Các phép toán trên Tensor ###\n")

add_result = x_data + x_data
print(f"Cộng x_data với chính nó:\n {add_result}\n")

mul_result = x_data * 5
print(f"Nhân x_data với 5:\n {mul_result}\n")

matmul_result = x_data @ x_data.T
print(f"Nhân ma trận x_data với x_data.T:\n {matmul_result}\n")


### Task 1.2: Các phép toán trên Tensor ###

Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])



In [6]:
print("\n### Task 1.3: Indexing và Slicing ###\n")

first_row = x_data[0]
print(f"Hàng đầu tiên: {first_row}\n")

second_col = x_data[:, 1]
print(f"Cột thứ hai: {second_col}\n")

element_1_1 = x_data[1, 1]
print(f"Giá trị ở hàng 2, cột 2: {element_1_1}\n")


### Task 1.3: Indexing và Slicing ###

Hàng đầu tiên: tensor([1, 2])

Cột thứ hai: tensor([2, 4])

Giá trị ở hàng 2, cột 2: 4



In [7]:
print("\n### Task 1.4: Thay đổi hình dạng Tensor ###\n")

tensor_4x4 = torch.rand(4, 4)
print(f"Tensor 4x4 ban đầu (shape {tensor_4x4.shape}):\n {tensor_4x4}\n")

tensor_16x1 = tensor_4x4.reshape(16, 1)
print(f"Tensor 16x1 (shape {tensor_16x1.shape}):\n {tensor_16x1}\n")


### Task 1.4: Thay đổi hình dạng Tensor ###

Tensor 4x4 ban đầu (shape torch.Size([4, 4])):
 tensor([[0.3455, 0.5944, 0.7700, 0.9099],
        [0.3548, 0.0268, 0.4290, 0.8073],
        [0.5546, 0.2015, 0.4127, 0.7020],
        [0.1543, 0.8620, 0.9666, 0.6071]])

Tensor 16x1 (shape torch.Size([16, 1])):
 tensor([[0.3455],
        [0.5944],
        [0.7700],
        [0.9099],
        [0.3548],
        [0.0268],
        [0.4290],
        [0.8073],
        [0.5546],
        [0.2015],
        [0.4127],
        [0.7020],
        [0.1543],
        [0.8620],
        [0.9666],
        [0.6071]])



In [8]:
print("\n--- Phần 2: Tự động tính Đạo hàm với autograd ---\n")

print("### Task 2.1: Thực hành với autograd ###\n")

x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"grad_fn của y: {y.grad_fn}")

z = y * y * 3
print(f"z: {z}")

z.backward() 

print(f"Đạo hàm của z theo x (x.grad): {x.grad}")

print("\n=== Trả lời câu hỏi Task 2.1 ===\n")
print("Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?\n")
print(
"""
Trả lời: 
Việc gọi `z.backward()` một lần nữa sẽ gây ra lỗi `RuntimeError: grad can be implicitly created only for scalar outputs`.

Tại sao?
Khi bạn gọi `.backward()` lần đầu tiên, PyTorch xây dựng một biểu đồ tính toán (computation graph) để tính đạo hàm. Sau khi tính toán xong, để tiết kiệm bộ nhớ, PyTorch sẽ **xóa biểu đồ này đi**.
Do đó, khi bạn gọi `z.backward()` lần thứ hai, biểu đồ cần thiết để tính đạo hàm không còn tồn tại, dẫn đến lỗi.
(Nếu bạn muốn giữ lại biểu đồ để gọi .backward() nhiều lần, bạn phải chỉ định `z.backward(retain_graph=True)` ở lần gọi đầu tiên).
"""
)


--- Phần 2: Tự động tính Đạo hàm với autograd ---

### Task 2.1: Thực hành với autograd ###

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x7bf93b4685e0>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x (x.grad): tensor([18.])

=== Trả lời câu hỏi Task 2.1 ===

Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?


Trả lời: 
Việc gọi `z.backward()` một lần nữa sẽ gây ra lỗi `RuntimeError: grad can be implicitly created only for scalar outputs`.

Tại sao?
Khi bạn gọi `.backward()` lần đầu tiên, PyTorch xây dựng một biểu đồ tính toán (computation graph) để tính đạo hàm. Sau khi tính toán xong, để tiết kiệm bộ nhớ, PyTorch sẽ **xóa biểu đồ này đi**.
Do đó, khi bạn gọi `z.backward()` lần thứ hai, biểu đồ cần thiết để tính đạo hàm không còn tồn tại, dẫn đến lỗi.
(Nếu bạn muốn giữ lại biểu đồ để gọi .backward() nhiều lần, bạn phải chỉ định `z.backward(retain_graph=True)` ở lần gọi đầu tiên

In [9]:
print("\n--- Phần 3: Xây dựng Mô hình đầu tiên với torch.nn ---\n")

print("### Task 3.1: Lớp nn.Linear ###\n")

linear_layer = torch.nn.Linear(in_features=5, out_features=2)

input_tensor = torch.randn(3, 5)

output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output: \n {output}\n")


--- Phần 3: Xây dựng Mô hình đầu tiên với torch.nn ---

### Task 3.1: Lớp nn.Linear ###

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output: 
 tensor([[ 0.3865, -0.4625],
        [ 0.3342,  0.0089],
        [ 0.7753, -0.0975]], grad_fn=<AddmmBackward0>)



In [10]:
print("\n### Task 3.2: Lớp nn.Embedding ###\n")

embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

input_indices = torch.LongTensor([1, 5, 0, 8])

embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings: \n {embeddings}\n")


### Task 3.2: Lớp nn.Embedding ###

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings: 
 tensor([[-1.5606, -1.6706,  0.8471],
        [ 1.3543,  0.3644, -1.0672],
        [-2.2414,  0.6837,  1.0970],
        [ 0.3271,  1.5846,  0.2833]], grad_fn=<EmbeddingBackward0>)



In [11]:
print("\n### Task 3.3: Kết hợp thành một nn.Module ###\n")

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
print(f"Mô hình đã khởi tạo:\n {model}\n")

input_data = torch.LongTensor([[1, 2, 5, 9]])
print(f"Input data shape: {input_data.shape}")

output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")
print(f"Model output data:\n {output_data}\n")



### Task 3.3: Kết hợp thành một nn.Module ###

Mô hình đã khởi tạo:
 MyFirstModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (activation): ReLU()
  (output_layer): Linear(in_features=8, out_features=2, bias=True)
)

Input data shape: torch.Size([1, 4])
Model output shape: torch.Size([1, 4, 2])
Model output data:
 tensor([[[-0.0704,  0.1147],
         [-0.2358,  0.0922],
         [-0.1243,  0.4964],
         [ 0.0361,  0.3644]]], grad_fn=<ViewBackward0>)

